### PR TITLE
Model scaffolding

### PR DESCRIPTION
**Pull request by jasontwong**
New and improved installation process with model scaffolding generator!

### CODE REVIEW

**Comment by Mrjaco12** [comment]
I think it would be worth taking some time to see if we could convert these .rb field to .erb files so hound doesn't freak. Also seems like a better structure overall.

**Comment by squaresurf** [comment]
I'm loving houndci!

**Comment by Mrjaco12** [comment]
:dancer: 

:+1:

**Comment by Mrjaco12** [comment]
:dog2:

**Comment by handerson** [comment]
:+1:

**Pull request merged**
